/**
 * strategy.js — 雙軌制自組強勢 ETF 策略選股引擎
 * Track A: 全市場績優股 GARP Top 10
 * Track B: 產業資金熱點池 Sector Momentum
 * 
 * Reads live data from js/strategy_data.json (generated by Python auto_screener.py)
 * Falls back to embedded mock data if JSON is unavailable.
 */

(function () {
    'use strict';

    // Chart.js Color Palette
    const PIE_COLORS = [
        '#10b981', '#06b6d4', '#8b5cf6', '#f59e0b', '#ec4899',
        '#6366f1', '#14b8a6', '#f97316', '#a855f7', '#ef4444',
        '#64748b'
    ];

    const HEAT_COLORS = {
        hot: '#ef4444',
        warm: '#f59e0b',
        cold: '#3b82f6'
    };

    let etfPieChart = null;
    let strategyData = null; // loaded from JSON

    // ============================================================
    // Fallback mock data (used only if JSON fetch fails)
    // ============================================================
    const FALLBACK_DATA = {
        generatedAt: '(模擬資料 — 請先執行 update_strategy.bat 抓取真實數據)',
        stockCount: 10,
        sectorCount: 0,
        fundamentalTop10: [
            { rank: 1, symbol: '3017', name: '奇鋐', sector: '散熱', price: 610, targetPrice: 850, upside: 39.3, pe: 22.5, eps: 27.1, revenueGrowth: 65, dividendYield: 1.8, score: 78, evaluation: 'cheap', techStatus: 'bull', techNote: '季線上揚 / MACD紅柱' },
            { rank: 2, symbol: '2382', name: '廣達', sector: 'AI伺服器', price: 285, targetPrice: 380, upside: 33.3, pe: 20.1, eps: 14.2, revenueGrowth: 72, dividendYield: 2.5, score: 75, evaluation: 'cheap', techStatus: 'bull', techNote: '季線上揚 / KD多方' },
            { rank: 3, symbol: '2330', name: '台積電', sector: '晶圓代工', price: 820, targetPrice: 1050, upside: 28.0, pe: 21.8, eps: 37.6, revenueGrowth: 55, dividendYield: 1.7, score: 70, evaluation: 'fair', techStatus: 'bull', techNote: '季線上揚 / 多頭排列' },
        ],
        hotSectors: []
    };

    // ============================================================
    // Tab switching
    // ============================================================
    function initTabs() {
        document.querySelectorAll('.strat-tab').forEach(tab => {
            tab.addEventListener('click', () => {
                document.querySelectorAll('.strat-tab').forEach(t => t.classList.remove('active'));
                tab.classList.add('active');
                const mode = tab.dataset.mode;
                document.querySelectorAll('.strat-panel').forEach(p => p.classList.remove('active'));
                const panel = document.getElementById(`panel-${mode}`);
                if (panel) panel.classList.add('active');
            });
        });
    }

    // ============================================================
    // Load data from JSON
    // ============================================================
    async function loadStrategyData() {
        try {
            const resp = await fetch('js/strategy_data.json?t=' + Date.now());
            if (!resp.ok) throw new Error('File not found');
            strategyData = await resp.json();
            console.log('[Strategy] Loaded real data from strategy_data.json');
        } catch (e) {
            console.warn('[Strategy] Could not load strategy_data.json, using fallback:', e.message);
            strategyData = FALLBACK_DATA;
        }

        // Update timestamp display
        const tsEl = document.getElementById('data-timestamp');
        if (tsEl) tsEl.textContent = strategyData.generatedAt || '尚未更新';

        const countEl = document.getElementById('data-stock-count');
        if (countEl) countEl.textContent = strategyData.stockCount || 0;

        renderFundamentalTable(strategyData.fundamentalTop10 || []);
        renderSectorHeatmap(strategyData.hotSectors || []);
    }

    // ============================================================
    // TRACK A: Render Fundamental Top 10 Table
    // ============================================================
    function renderFundamentalTable(stocks) {
        const tbody = document.getElementById('stock-tbody');
        if (!tbody) return;

        if (stocks.length === 0) {
            tbody.innerHTML = '<tr><td colspan="13" style="text-align:center; padding:40px; color:var(--text-dim);">尚無資料。請先執行 update_strategy.bat 抓取真實數據。</td></tr>';
            return;
        }

        let html = '';
        stocks.forEach(st => {
            const rankDisplay = st.rank <= 3
                ? ['🥇', '🥈', '🥉'][st.rank - 1]
                : `#${st.rank}`;

            const evalBadge = {
                cheap: '<span class="badge-cheap">🟢 便宜</span>',
                fair: '<span class="badge-fair">🟡 合理</span>',
                expensive: '<span class="badge-expensive">🔴 偏貴</span>'
            }[st.evaluation] || '<span class="badge-fair">🟡 合理</span>';

            const techClass = { bull: 'tech-bull', neutral: 'tech-neutral', bear: 'tech-bear' }[st.techStatus] || 'tech-neutral';
            const techIcon = { bull: '📈', neutral: '📊', bear: '📉' }[st.techStatus] || '📊';

            const checked = st.evaluation !== 'expensive' ? 'checked' : '';

            html += `<tr data-symbol="${st.symbol}" class="${st.evaluation === 'expensive' && !checked ? 'row-disabled' : ''}">
                <td><input type="checkbox" class="stock-check" data-symbol="${st.symbol}" data-track="fundamental" ${checked}></td>
                <td><span class="rank-medal">${rankDisplay}</span></td>
                <td style="text-align:left; font-weight:600;">
                    <span style="color:var(--accent-cyan)">${st.symbol}</span>
                    <span style="color:var(--text-primary); margin-left:4px;">${st.name}</span>
                    <br><span style="font-size:0.75rem; color:var(--text-dim);">${st.sector || ''}</span>
                </td>
                <td>${evalBadge}</td>
                <td style="font-weight:600; font-family:var(--font-en);">$${Number(st.price).toLocaleString()}</td>
                <td style="color:var(--accent-cyan); font-family:var(--font-en);">${st.targetPrice ? '$' + Number(st.targetPrice).toLocaleString() : '-'}</td>
                <td style="color:${st.upside >= 20 ? 'var(--accent-green)' : st.upside >= 10 ? 'var(--accent-yellow)' : 'var(--accent-red)'}; font-weight:600;">${st.upside > 0 ? '+' : ''}${st.upside}%</td>
                <td style="font-family:var(--font-en);">${st.pe ? st.pe.toFixed(1) + 'x' : '-'}</td>
                <td style="font-family:var(--font-en);">${st.eps ? '$' + st.eps.toFixed(1) : '-'}</td>
                <td style="color:var(--accent-green); font-weight:600;">${st.revenueGrowth ? '+' + st.revenueGrowth + '%' : '-'}</td>
                <td style="color:var(--accent-purple);">${st.dividendYield || 0}%</td>
                <td style="font-family:var(--font-en); font-weight:600; color:var(--accent-yellow);">${st.score ? st.score.toFixed(0) : '-'}</td>
                <td class="${techClass}" title="${st.techNote || ''}">${techIcon} ${(st.techNote || '').split('/')[0].trim()}</td>
            </tr>`;
        });

        tbody.innerHTML = html;

        // Bind checkbox toggles
        tbody.querySelectorAll('.stock-check').forEach(cb => {
            cb.addEventListener('change', e => {
                const row = e.target.closest('tr');
                row.classList.toggle('row-disabled', !e.target.checked);
            });
        });
    }

    // ============================================================
    // TRACK B: Render Sector Heatmap
    // ============================================================
    function renderSectorHeatmap(sectors) {
        const container = document.getElementById('sector-heatmap');
        if (!container) return;

        if (sectors.length === 0) {
            container.innerHTML = '<div style="text-align:center; padding:40px; color:var(--text-dim);">尚無板塊資料。請先執行 update_strategy.bat 抓取真實數據。</div>';
            return;
        }

        let html = '';

        // --- Heatmap Grid ---
        html += '<div class="heatmap-grid">';
        sectors.forEach(s => {
            const heatIcon = { hot: '🔥', warm: '🌡️', cold: '❄️' }[s.heat] || '❓';
            const heatColor = HEAT_COLORS[s.heat] || '#64748b';
            const borderColor = s.heat === 'hot' ? 'rgba(239,68,68,0.4)' : s.heat === 'warm' ? 'rgba(245,158,11,0.3)' : 'rgba(59,130,246,0.2)';

            html += `<div class="heatmap-card" style="border-color:${borderColor};" data-sector="${s.sector}">
                <div class="heatmap-card-header">
                    <span class="heatmap-icon">${heatIcon}</span>
                    <span class="heatmap-name">${s.sector}</span>
                    <span class="heatmap-score" style="color:${heatColor};">${s.momentum_score > 0 ? '+' : ''}${s.momentum_score}</span>
                </div>
                <div class="heatmap-stats">
                    <span title="5日平均漲幅">5日 <b style="color:${s.avg_return_5d >= 0 ? 'var(--accent-green)' : 'var(--accent-red)'};">${s.avg_return_5d >= 0 ? '+' : ''}${s.avg_return_5d}%</b></span>
                    <span title="10日平均漲幅">10日 <b style="color:${s.avg_return_10d >= 0 ? 'var(--accent-green)' : 'var(--accent-red)'};">${s.avg_return_10d >= 0 ? '+' : ''}${s.avg_return_10d}%</b></span>
                    <span title="20日平均漲幅">20日 <b style="color:${s.avg_return_20d >= 0 ? 'var(--accent-green)' : 'var(--accent-red)'};">${s.avg_return_20d >= 0 ? '+' : ''}${s.avg_return_20d}%</b></span>
                    <span title="近5日量能相對先前20日的倍率">量能 <b style="color:var(--accent-cyan);">${s.volume_spike}x</b></span>
                </div>
            </div>`;
        });
        html += '</div>';

        container.innerHTML = html;

        // --- Click to expand sector leaders ---
        container.querySelectorAll('.heatmap-card').forEach(card => {
            card.addEventListener('click', () => {
                const sectorName = card.dataset.sector;
                const sectorData = sectors.find(s => s.sector === sectorName);
                if (sectorData) {
                    renderSectorLeaders(sectorName, sectorData.leaders || []);
                }
                // Toggle active state
                container.querySelectorAll('.heatmap-card').forEach(c => c.classList.remove('heatmap-active'));
                card.classList.add('heatmap-active');
            });
        });

        // Auto-expand hottest sector
        if (sectors.length > 0) {
            const hottest = container.querySelector('.heatmap-card');
            if (hottest) hottest.click();
        }
    }

    function renderSectorLeaders(sectorName, leaders) {
        const container = document.getElementById('sector-leaders');
        if (!container) return;

        if (leaders.length === 0) {
            container.innerHTML = `<p style="color:var(--text-dim); padding:20px;">「${sectorName}」板塊內暫無詳細個股資料。</p>`;
            return;
        }

        let html = `<h3 style="margin-bottom:12px;">🎯 ${sectorName} — 板塊領軍股 Top ${leaders.length}</h3>`;
        html += `<div class="strat-table-wrap"><table class="strat-table"><thead><tr>
            <th>選</th><th>代號/名稱</th><th>股價</th><th>5日漲幅</th><th>外資目標價</th><th>潛在空間</th><th>本益比</th><th>EPS</th><th>殖利率</th><th>技術面</th>
        </tr></thead><tbody>`;

        leaders.forEach(l => {
            const techClass = { bull: 'tech-bull', neutral: 'tech-neutral', bear: 'tech-bear' }[l.techStatus] || 'tech-neutral';
            const techIcon = { bull: '📈', neutral: '📊', bear: '📉' }[l.techStatus] || '📊';

            html += `<tr>
                <td><input type="checkbox" class="stock-check" data-symbol="${l.symbol}" data-track="sector" data-price="${l.current_price}"></td>
                <td style="text-align:left; font-weight:600;">
                    <span style="color:var(--accent-cyan)">${l.symbol}</span>
                    <span style="margin-left:4px;">${l.name}</span>
                </td>
                <td style="font-family:var(--font-en); font-weight:600;">$${Number(l.current_price).toLocaleString()}</td>
                <td style="color:${l.return_5d >= 0 ? 'var(--accent-green)' : 'var(--accent-red)'}; font-weight:600;">${l.return_5d >= 0 ? '+' : ''}${l.return_5d}%</td>
                <td style="color:var(--accent-cyan); font-family:var(--font-en);">${l.targetPrice ? '$' + Number(l.targetPrice).toLocaleString() : '-'}</td>
                <td style="color:${l.upside >= 20 ? 'var(--accent-green)' : l.upside >= 10 ? 'var(--accent-yellow)' : 'var(--accent-red)'};">${l.upside > 0 ? '+' : ''}${l.upside}%</td>
                <td style="font-family:var(--font-en);">${l.pe ? l.pe + 'x' : '-'}</td>
                <td style="font-family:var(--font-en);">${l.eps ? '$' + l.eps : '-'}</td>
                <td style="color:var(--accent-purple);">${l.dividendYield || 0}%</td>
                <td class="${techClass}" title="${l.techNote || ''}">${techIcon} ${(l.techNote || '').split('/')[0].trim()}</td>
            </tr>`;
        });

        html += '</tbody></table></div>';
        container.innerHTML = html;
    }

    // ============================================================
    // Budget Allocation Engine (works with BOTH tracks)
    // ============================================================
    function calculateAllocation() {
        const budgetInput = document.getElementById('budget-input');
        const budget = parseFloat(budgetInput.value) || 0;

        if (budget <= 0) {
            alert('請輸入有效的投資預算金額！');
            return;
        }

        // Collect ALL checked stocks across both tracks
        const checkboxes = document.querySelectorAll('.stock-check:checked');
        if (checkboxes.length === 0) {
            alert('請至少勾選一檔股票！（可從「穩健成長池」或「資金熱點池」中勾選）');
            return;
        }

        const selectedStocks = [];
        const seenSymbols = new Set();

        checkboxes.forEach(cb => {
            const sym = cb.dataset.symbol;
            if (seenSymbols.has(sym)) return;
            seenSymbols.add(sym);

            const track = cb.dataset.track;
            let stockInfo = null;

            if (track === 'fundamental') {
                stockInfo = (strategyData.fundamentalTop10 || []).find(s => s.symbol === sym);
            } else {
                // Search in sector leaders
                for (const sec of (strategyData.hotSectors || [])) {
                    const found = (sec.leaders || []).find(l => l.symbol === sym);
                    if (found) {
                        stockInfo = { symbol: found.symbol, name: found.name, price: found.current_price, upside: found.upside || 0 };
                        break;
                    }
                }
            }

            if (stockInfo) {
                selectedStocks.push({
                    symbol: stockInfo.symbol,
                    name: stockInfo.name,
                    price: stockInfo.price || stockInfo.current_price || 0,
                    upside: stockInfo.upside || 0,
                    track: track
                });
            }
        });

        if (selectedStocks.length === 0) {
            alert('無法取得所選股票的價格資訊！');
            return;
        }

        const perStockBudget = Math.floor(budget / selectedStocks.length);

        const allocations = [];
        let totalInvested = 0;

        selectedStocks.forEach(st => {
            if (st.price <= 0) return;
            const shares = Math.floor(perStockBudget / st.price);
            const cost = shares * st.price;
            const weight = budget > 0 ? (cost / budget * 100) : 0;
            totalInvested += cost;

            allocations.push({
                ...st,
                allocShares: shares,
                allocCost: Math.round(cost),
                allocWeight: weight
            });
        });

        const idleCash = Math.round(budget - totalInvested);
        const utilization = budget > 0 ? ((totalInvested / budget) * 100) : 0;

        renderAllocationResults(allocations, Math.round(budget), Math.round(totalInvested), idleCash, utilization);
    }

    // ============================================================
    // Render allocation results
    // ============================================================
    function renderAllocationResults(allocations, budget, totalInvested, idleCash, utilization) {
        const container = document.getElementById('alloc-results');
        container.classList.add('active');
        container.scrollIntoView({ behavior: 'smooth', block: 'start' });

        // Summary stats
        document.getElementById('stat-budget').textContent = 'NT$ ' + budget.toLocaleString();
        document.getElementById('stat-invested').textContent = 'NT$ ' + totalInvested.toLocaleString();
        document.getElementById('stat-idle').textContent = 'NT$ ' + idleCash.toLocaleString();
        document.getElementById('stat-utilization').textContent = utilization.toFixed(1) + '%';
        document.getElementById('stat-count').textContent = allocations.length + ' 檔';

        // Table
        const tbody = document.getElementById('alloc-tbody');
        let html = '';
        allocations.forEach(a => {
            const trackBadge = a.track === 'fundamental'
                ? '<span style="font-size:0.7rem; background:rgba(16,185,129,0.15); color:var(--accent-green); padding:2px 6px; border-radius:10px;">穩健</span>'
                : '<span style="font-size:0.7rem; background:rgba(239,68,68,0.15); color:var(--accent-red); padding:2px 6px; border-radius:10px;">波段</span>';

            html += `<tr>
                <td style="font-weight:600; color:var(--accent-cyan);">${a.symbol} ${a.name} ${trackBadge}</td>
                <td style="font-family:var(--font-en);">$${Number(a.price).toLocaleString()}</td>
                <td style="font-weight:700; color:var(--strat-secondary); font-size:1.05rem;">${a.allocShares.toLocaleString()} 股</td>
                <td style="font-family:var(--font-en); font-weight:600;">NT$ ${a.allocCost.toLocaleString()}</td>
                <td style="font-family:var(--font-en);">${a.allocWeight.toFixed(1)}%</td>
                <td style="color:${a.upside >= 20 ? 'var(--accent-green)' : a.upside >= 10 ? 'var(--accent-yellow)' : 'var(--accent-red)'};">${a.upside > 0 ? '+' : ''}${a.upside}%</td>
            </tr>`;
        });

        html += `<tr style="background:rgba(16,185,129,0.08);">
            <td style="font-weight:700;">合計</td>
            <td></td>
            <td style="font-weight:700;">${allocations.reduce((s, a) => s + a.allocShares, 0).toLocaleString()} 股</td>
            <td style="font-weight:700; color:var(--strat-secondary);">NT$ ${totalInvested.toLocaleString()}</td>
            <td style="font-weight:700;">${utilization.toFixed(1)}%</td>
            <td></td>
        </tr>`;

        if (idleCash > 0) {
            html += `<tr style="color:var(--text-dim);">
                <td>💵 剩餘閒置現金</td><td></td><td></td>
                <td>NT$ ${idleCash.toLocaleString()}</td>
                <td>${(idleCash / budget * 100).toFixed(1)}%</td><td></td>
            </tr>`;
        }

        tbody.innerHTML = html;

        // Pie chart
        renderETFPieChart(allocations, idleCash);
    }

    function renderETFPieChart(allocations, idleCash) {
        const ctx = document.getElementById('chart-etf');
        if (!ctx) return;

        const labels = allocations.map(a => `${a.symbol} ${a.name}`);
        const data = allocations.map(a => a.allocCost);
        const colors = allocations.map((_, i) => PIE_COLORS[i % PIE_COLORS.length]);

        if (idleCash > 0) {
            labels.push('💵 閒置現金');
            data.push(idleCash);
            colors.push('#334155');
        }

        const total = data.reduce((s, v) => s + v, 0);

        const tooltipCallback = function (context) {
            const val = context.raw;
            const pct = total > 0 ? ((val / total) * 100).toFixed(1) : 0;
            return ` NT$ ${val.toLocaleString()} (${pct}%)`;
        };

        if (etfPieChart) {
            etfPieChart.data.labels = labels;
            etfPieChart.data.datasets[0].data = data;
            etfPieChart.data.datasets[0].backgroundColor = colors;
            etfPieChart.options.plugins.tooltip.callbacks.label = tooltipCallback;
            etfPieChart.update();
        } else {
            etfPieChart = new Chart(ctx, {
                type: 'doughnut',
                data: { labels, datasets: [{ data, backgroundColor: colors, borderWidth: 1, borderColor: 'rgba(6,6,15,0.6)', hoverOffset: 6 }] },
                options: {
                    responsive: true, maintainAspectRatio: false, cutout: '60%',
                    plugins: { legend: { display: false }, tooltip: { callbacks: { label: tooltipCallback } } }
                }
            });
        }

        // Legend
        const legendEl = document.getElementById('pie-legend');
        if (legendEl) {
            let lh = '';
            allocations.forEach((a, i) => {
                lh += `<div class="pie-legend-item"><span class="pie-legend-dot" style="background:${colors[i]}"></span><span>${a.symbol} ${a.name}</span></div>`;
            });
            if (idleCash > 0) {
                lh += `<div class="pie-legend-item"><span class="pie-legend-dot" style="background:#334155"></span><span>💵 閒置現金</span></div>`;
            }
            legendEl.innerHTML = lh;
        }
    }

    // ============================================================
    // Init
    // ============================================================
    document.addEventListener('DOMContentLoaded', () => {
        initTabs();
        loadStrategyData();

        const btnCalc = document.getElementById('btn-calculate');
        if (btnCalc) btnCalc.addEventListener('click', calculateAllocation);

        const budgetInput = document.getElementById('budget-input');
        if (budgetInput) budgetInput.addEventListener('keydown', e => { if (e.key === 'Enter') calculateAllocation(); });
    });

})();
